### ISSUE TITLE
1 экран

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/recipes#18]
![Untitled](https://user-images.githubusercontent.com/42935142/81797995-c6c3f300-950f-11ea-8b9b-a14437fd3c7d.png)
1. Отступ контента больше справа, чем слева - Контент должен быть посередине
2. Плейсхолдер не долэжен быть курсивным.
3. Эти две подписи слишком важны, чтобы иметь такой маленький шрифт. Хорошо бы их h3 сделать хотя бы.
4. Слово "Вес" имеет слишком близкое расстояние к чекбоксу
5- 
5.1 Reset английское слово. Может лучше немецкое? 
5.2 Reset  все таки надо красным, и подвинуть его к "Kalorien berechnen"
5.3 "Kalorien berechnen" должно бы быть побудительно зеленым.
6. Контент не посередине

**Comment by h-shvedko** [comment]
1 - done
2 -lecker.de styling
3 - done
4 - done
5.1, 5.2- done
5.3 - styling of lecker.de
6 - done
