### ISSUE TITLE
2 экран

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/recipes#19]
1. Надо бы добавить тонкие разделительнрые вертикальные полоски между приемами пищи
2. Заголовок день выделить поярче h3
3. Все фото карточек должны быть обсолютно одинакового размера. Заголовки на одном уровне. Иконки цветные
4. Под заголовком должна стоять маленькая инструкция в виде примерно таком "Выберите одно блюдо из предложенных трёх на завтрак, обед и ужин."
5. Под заголовки колонок лучше дать яркие плашки. И продублировать для последующих дней заголовки
6. буква D пропущена
![Untitled2](https://user-images.githubusercontent.com/42935142/81800139-a5b0d180-9512-11ea-84f1-266737a39b08.png)

**Comment by h-shvedko** [comment]
1,2,3,4,6 - done

**Comment by h-shvedko** [comment]
5 - done
